-- MySQL Script generated by MySQL Workbench
-- Tue Jan  3 12:40:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP TABLE IF EXISTS `PruebaTalentAcquisition`.`movimiento` ;
DROP TABLE IF EXISTS `PruebaTalentAcquisition`.`cuenta` ;
DROP TABLE IF EXISTS `PruebaTalentAcquisition`.`cliente` ;
DROP TABLE IF EXISTS `PruebaTalentAcquisition`.`persona` ;
DROP TABLE IF EXISTS `PruebaTalentAcquisition`.`entidad` ;
-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema PruebaTalentAcquisition
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PruebaTalentAcquisition` ;

-- -----------------------------------------------------
-- Schema PruebaTalentAcquisition
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PruebaTalentAcquisition` DEFAULT CHARACTER SET utf8 ;
USE `PruebaTalentAcquisition` ;

-- -----------------------------------------------------
-- Table `PruebaTalentAcquisition`.`entidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PruebaTalentAcquisition`.`entidad` ;

CREATE TABLE IF NOT EXISTS `PruebaTalentAcquisition`.`entidad` (
  `iIdentidad` INT NOT NULL AUTO_INCREMENT,
  `tNombreentidad` VARCHAR(100) NOT NULL,
  `bEstado` BOOLEAN NOT NULL,
  `dtFechaCreacion` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`iIdentidad`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `PruebaTalentAcquisition`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PruebaTalentAcquisition`.`persona` ;

CREATE TABLE IF NOT EXISTS `PruebaTalentAcquisition`.`persona` (
  `iIdpersona` INT NOT NULL AUTO_INCREMENT,
  `tNombre` VARCHAR(100) NOT NULL,
  `tGenero` VARCHAR(1) NOT NULL,
  `iEdad` INT NOT NULL,
  `tIdentificacion` VARCHAR(45) NOT NULL,
  `tDireccion` VARCHAR(100) NOT NULL,
  `tTelefono` VARCHAR(45) NOT NULL,
  `entidad_iIdentidad` INT NOT NULL,
  `bEstado` BOOLEAN NOT NULL,
  `dtFechaCreacion` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`iIdpersona`),
  INDEX `fk_persona_entidad1_idx` (`entidad_iIdentidad` ASC) VISIBLE,
  CONSTRAINT `fk_persona_entidad1`
    FOREIGN KEY (`entidad_iIdentidad`)
    REFERENCES `PruebaTalentAcquisition`.`entidad` (`iIdentidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PruebaTalentAcquisition`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PruebaTalentAcquisition`.`cliente` ;

CREATE TABLE IF NOT EXISTS `PruebaTalentAcquisition`.`cliente` (
  `iIdcliente` INT NOT NULL AUTO_INCREMENT,
  `tContrasena` VARCHAR(200) NOT NULL,
  `bEstado` BOOLEAN NOT NULL,
  `persona_iIdpersona` INT NOT NULL,
  `dtFechaCreacion` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`iIdcliente`),
  INDEX `fk_cliente_persona1_idx` (`persona_iIdpersona` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_persona1`
    FOREIGN KEY (`persona_iIdpersona`)
    REFERENCES `PruebaTalentAcquisition`.`persona` (`iIdpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PruebaTalentAcquisition`.`cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PruebaTalentAcquisition`.`cuenta` ;

CREATE TABLE IF NOT EXISTS `PruebaTalentAcquisition`.`cuenta` (
  `iIdcuenta` INT NOT NULL AUTO_INCREMENT,
  `tNumerocuenta` VARCHAR(45) NOT NULL,
  `tTipocuenta` VARCHAR(50) NOT NULL,
  `iSaldoInicial` INT NOT NULL,
  `bEstado` BOOLEAN NOT NULL,
  `dtFechaCreacion` TIMESTAMP(3) NOT NULL,
  `iSaldo` INT NOT NULL,
  `cliente_iIdcliente` INT NOT NULL,
  PRIMARY KEY (`iIdcuenta`),
  INDEX `fk_cuenta_cliente1_idx` (`cliente_iIdcliente` ASC) VISIBLE,
  CONSTRAINT `fk_cuenta_cliente1`
    FOREIGN KEY (`cliente_iIdcliente`)
    REFERENCES `PruebaTalentAcquisition`.`cliente` (`iIdcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PruebaTalentAcquisition`.`movimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PruebaTalentAcquisition`.`movimiento` ;

CREATE TABLE IF NOT EXISTS `PruebaTalentAcquisition`.`movimiento` (
  `iIdmovimiento` INT NOT NULL AUTO_INCREMENT,
  `dtFecha` VARCHAR(45) NOT NULL,
  `imovimiento` INT NOT NULL,
  `tTipomovimiento` VARCHAR(45) NOT NULL,
  `bEstado` BOOLEAN NOT NULL,
  `dtFechaCreacion` TIMESTAMP(3) NOT NULL,
  `cuenta_iIdcuenta` INT NOT NULL,
  PRIMARY KEY (`iIdmovimiento`),
  INDEX `fk_movimiento_cuenta1_idx` (`cuenta_iIdcuenta` ASC) VISIBLE,
  CONSTRAINT `fk_movimiento_cuenta1`
    FOREIGN KEY (`cuenta_iIdcuenta`)
    REFERENCES `PruebaTalentAcquisition`.`cuenta` (`iIdcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- insert entidad
-- -----------------------------------------------------
-- insert Into entidad values(1,"Bancolombia",true);
-- insert Into entidad values(2,"Bbva",true);
-- insert Into entidad values(3,"Banco Pichincha",true);

insert Into entidad(`tNombreEntidad`,`bEstado`,`dtFechaCreacion`) values("Bancolombia",true,now());
insert Into entidad(`tNombreEntidad`,`bEstado`,`dtFechaCreacion`) values("BBVA",true,now());
insert Into entidad(`tNombreEntidad`,`bEstado`,`dtFechaCreacion`) values("Banco Pichincha",true,now());

-- -----------------------------------------------------
-- insert persona
-- -----------------------------------------------------

-- insert persona relacionado con bancolombia
insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Jose Lema","M",30,"101010101011","Otavalo sn y principal","098254785",1,true,now());

insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Marianela Montalvo","F",20,"101010101012","Amazonas y NNUU","097548965",1,true,now());

insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Juan Osorio ","M",40,"101010101013","13 junio y Equinoccial","098874587",1,true,now());

-- insert persona relacionado con BBVA
insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Jose Lema","M",30,"101010101011","Otavalo sn y principal","098254785",2,true,now());

insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Marianela Montalvo","F",20,"101010101012","Amazonas y NNUU","097548965",2,true,now());

insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Juan Osorio ","M",40,"101010101013","13 junio y Equinoccial","098874587",2,true,now());

-- insert persona relacionado con el banco Pichincha
insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Jose Lema","M",30,"101010101011","Otavalo sn y principal","098254785",3,true,now());

insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Marianela Montalvo","F",20,"101010101012","Amazonas y NNUU","097548965",3,true,now());

insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Juan Osorio ","M",40,"101010101013","13 junio y Equinoccial","098874587",3,true,now());

insert Into cliente(`tContrasena`,`bEstado`,`persona_iIdpersona`,`dtFechaCreacion`) 
values("123",true,1,now());

SELECT CURTIME(3);