-- MySQL Script generated by MySQL Workbench
-- Tue Jan  3 12:40:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema PruebaTalentAcquisition
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PruebaTalentAcquisition` ;

-- -----------------------------------------------------
-- Schema PruebaTalentAcquisition
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PruebaTalentAcquisition` DEFAULT CHARACTER SET utf8 ;
USE `PruebaTalentAcquisition` ;

-- -----------------------------------------------------
-- Table `PruebaTalentAcquisition`.`Entidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PruebaTalentAcquisition`.`Entidad` ;

CREATE TABLE IF NOT EXISTS `PruebaTalentAcquisition`.`Entidad` (
  `iIdEntidad` INT NOT NULL AUTO_INCREMENT,
  `tNombreEntidad` VARCHAR(100) NOT NULL,
  `bEstado` BOOLEAN NOT NULL,
  `dtFechaCreacion` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`iIdEntidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PruebaTalentAcquisition`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PruebaTalentAcquisition`.`Persona` ;

CREATE TABLE IF NOT EXISTS `PruebaTalentAcquisition`.`Persona` (
  `iIdpersona` INT NOT NULL AUTO_INCREMENT,
  `tNombre` VARCHAR(100) NOT NULL,
  `tGenero` VARCHAR(1) NOT NULL,
  `iEdad` INT NOT NULL,
  `tIdentificacion` VARCHAR(45) NOT NULL,
  `tDireccion` VARCHAR(100) NOT NULL,
  `tTelefono` VARCHAR(45) NOT NULL,
  `Entidad_iIdEntidad` INT NOT NULL,
  `bEstado` BOOLEAN NOT NULL,
  `dtFechaCreacion` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`iIdpersona`),
  INDEX `fk_Persona_Entidad1_idx` (`Entidad_iIdEntidad` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_Entidad1`
    FOREIGN KEY (`Entidad_iIdEntidad`)
    REFERENCES `PruebaTalentAcquisition`.`Entidad` (`iIdEntidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PruebaTalentAcquisition`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PruebaTalentAcquisition`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `PruebaTalentAcquisition`.`Cliente` (
  `iIdCliente` INT NOT NULL AUTO_INCREMENT,
  `tContrasena` VARCHAR(200) NOT NULL,
  `bEstado` BOOLEAN NOT NULL,
  `Persona_iIdpersona` INT NOT NULL,
  `dtFechaCreacion` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`iIdCliente`),
  INDEX `fk_Cliente_Persona1_idx` (`Persona_iIdpersona` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Persona1`
    FOREIGN KEY (`Persona_iIdpersona`)
    REFERENCES `PruebaTalentAcquisition`.`Persona` (`iIdpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PruebaTalentAcquisition`.`Cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PruebaTalentAcquisition`.`Cuenta` ;

CREATE TABLE IF NOT EXISTS `PruebaTalentAcquisition`.`Cuenta` (
  `iIdCuenta` INT NOT NULL AUTO_INCREMENT,
  `tNumeroCuenta` VARCHAR(45) NOT NULL,
  `tTipoCuenta` VARCHAR(50) NOT NULL,
  `iSaldoInicial` INT NOT NULL,
  `bEstado` BOOLEAN NOT NULL,
  `dtFechaCreacion` TIMESTAMP(3) NOT NULL,
  `iSaldo` INT NOT NULL,
  `Cliente_iIdCliente` INT NOT NULL,
  PRIMARY KEY (`iIdCuenta`),
  INDEX `fk_Cuenta_Cliente1_idx` (`Cliente_iIdCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cuenta_Cliente1`
    FOREIGN KEY (`Cliente_iIdCliente`)
    REFERENCES `PruebaTalentAcquisition`.`Cliente` (`iIdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PruebaTalentAcquisition`.`Movimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PruebaTalentAcquisition`.`Movimiento` ;

CREATE TABLE IF NOT EXISTS `PruebaTalentAcquisition`.`Movimiento` (
  `iIdMovimiento` INT NOT NULL AUTO_INCREMENT,
  `dtFecha` VARCHAR(45) NOT NULL,
  `iMovimiento` INT NOT NULL,
  `tTipoMovimiento` VARCHAR(45) NOT NULL,
  `bEstado` BOOLEAN NOT NULL,
  `dtFechaCreacion` TIMESTAMP(3) NOT NULL,
  `Cuenta_iIdCuenta` INT NOT NULL,
  PRIMARY KEY (`iIdMovimiento`),
  INDEX `fk_Movimiento_Cuenta1_idx` (`Cuenta_iIdCuenta` ASC) VISIBLE,
  CONSTRAINT `fk_Movimiento_Cuenta1`
    FOREIGN KEY (`Cuenta_iIdCuenta`)
    REFERENCES `PruebaTalentAcquisition`.`Cuenta` (`iIdCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- insert Entidad
-- -----------------------------------------------------
-- insert Into entidad values(1,"Bancolombia",true);
-- insert Into entidad values(2,"Bbva",true);
-- insert Into entidad values(3,"Banco Pichincha",true);

insert Into entidad(`tNombreEntidad`,`bEstado`,`dtFechaCreacion`) values("Bancolombia",true,now());
insert Into entidad(`tNombreEntidad`,`bEstado`,`dtFechaCreacion`) values("BBVA",true,now());
insert Into entidad(`tNombreEntidad`,`bEstado`,`dtFechaCreacion`) values("Banco Pichincha",true,now());

-- -----------------------------------------------------
-- insert Persona
-- -----------------------------------------------------

-- insert Persona relacionado con bancolombia
insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Jose Lema","M",30,"101010101011","Otavalo sn y principal","098254785",1,true,now());

insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Marianela Montalvo","F",20,"101010101012","Amazonas y NNUU","097548965",1,true,now());

insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Juan Osorio ","M",40,"101010101013","13 junio y Equinoccial","098874587",1,true,now());

-- insert Persona relacionado con BBVA
insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Jose Lema","M",30,"101010101011","Otavalo sn y principal","098254785",2,true,now());

insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Marianela Montalvo","F",20,"101010101012","Amazonas y NNUU","097548965",2,true,now());

insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Juan Osorio ","M",40,"101010101013","13 junio y Equinoccial","098874587",2,true,now());

-- insert Persona relacionado con el banco Pichincha
insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Jose Lema","M",30,"101010101011","Otavalo sn y principal","098254785",3,true,now());

insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Marianela Montalvo","F",20,"101010101012","Amazonas y NNUU","097548965",3,true,now());

insert Into persona(`tNombre`,`tGenero`,`iEdad`,`tIdentificacion`,`tDireccion`,`tTelefono`,`Entidad_iIdEntidad`,`bEstado`,`dtFechaCreacion`) 
values("Juan Osorio ","M",40,"101010101013","13 junio y Equinoccial","098874587",3,true,now());

select * from entidad;
select * from persona;

insert Into cliente(`tContrasena`,`bEstado`,`Persona_iIdpersona`,`dtFechaCreacion`) 
values("123",true,1,now());

SELECT CURTIME(3);