version: "3.9"
services:
  mysql_container:
    container_name: mysql_container
    image: mysql
    networks:
      - network_talent_acquisition
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD : JOSELE2015
    volumes:
      - MysqlTalentAcquisition:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
      # postgres -> /var/lib/postgresql/data
networks:
  network_talent_acquisition:
volumes:
  MysqlTalentAcquisition:
